### ISSUE TITLE
Issue with MoneyConverters(French)

### ISSUE THREAD

**Issue by JDVB** [allegro/tradukisto#29] opened 2019-02-05 08:04 UTC
Hi there, I've been looking all over the web for a library that fits my needs.
I was pleasantly surprised to come across yours.
The issue I'm facing now is the following: 
I would like to convert a number(currency value) to its word representation, so I follow the steps as described in the README file. But for some reason the MoneyConverters enum does not contain a value for French even though a Container is available for it.
Is this an oversight or is it done on purpose?

My best regards

JDVB

**Comment by dorians** [comment] 2019-02-05 10:05
Thanks a lot for reporting this issue. I've created a fix for it. Let's wait for @wjur who'll release it.

**Comment by wjur** [comment] 2019-02-07 13:26
@JDVB the issue is fixed in 1.7.1. Thank you @dorians for the fix!

**Closed** 2019-02-11 12:21 UTC
